/* Generated by tools/vendor_nimble_esp32.py -- do not edit.
 *
 * The NimBLE host configuration for the original ESP32, frozen to the
 * values Arduino-ESP32 3.3.11 uses for esp32s3.
 * Keeping them identical is what lets the original ESP32 behave like the
 * other targets; see docs/PLAN_ESP32.ja.md. Overriding any of them would
 * change the vendored headers without changing this file's assumptions,
 * so an override is rejected instead of silently accepted.
 */

#ifndef ESPBLE_NIMBLE_CONFIG_H
#define ESPBLE_NIMBLE_CONFIG_H

#include <sdkconfig.h>

#ifdef CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT
#error "CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT 1

#ifdef CONFIG_BT_NIMBLE_ACL_BUF_COUNT
#error "CONFIG_BT_NIMBLE_ACL_BUF_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ACL_BUF_COUNT 24

#ifdef CONFIG_BT_NIMBLE_ACL_BUF_SIZE
#error "CONFIG_BT_NIMBLE_ACL_BUF_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ACL_BUF_SIZE 255

#ifdef CONFIG_BT_NIMBLE_ANS_SERVICE
#error "CONFIG_BT_NIMBLE_ANS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ANS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_ATT_MAX_PREP_ENTRIES
#error "CONFIG_BT_NIMBLE_ATT_MAX_PREP_ENTRIES is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ATT_MAX_PREP_ENTRIES 64

#ifdef CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU
#error "CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ATT_PREFERRED_MTU 256

#ifdef CONFIG_BT_NIMBLE_BAS_SERVICE
#error "CONFIG_BT_NIMBLE_BAS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_BAS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_CHK_HOST_STATUS
#error "CONFIG_BT_NIMBLE_CHK_HOST_STATUS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_CHK_HOST_STATUS 1

#ifdef CONFIG_BT_NIMBLE_COEX_PHY_CODED_TX_RX_TLIM_DIS
#error "CONFIG_BT_NIMBLE_COEX_PHY_CODED_TX_RX_TLIM_DIS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_COEX_PHY_CODED_TX_RX_TLIM_DIS 1

#ifdef CONFIG_BT_NIMBLE_CPFD_CAFD
#error "CONFIG_BT_NIMBLE_CPFD_CAFD is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_CPFD_CAFD 1

#ifdef CONFIG_BT_NIMBLE_CTS_SERVICE
#error "CONFIG_BT_NIMBLE_CTS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_CTS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_DIS_SERVICE
#error "CONFIG_BT_NIMBLE_DIS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_DIS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_DTM_MODE_TEST
#error "CONFIG_BT_NIMBLE_DTM_MODE_TEST is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_DTM_MODE_TEST 1

#ifdef CONFIG_BT_NIMBLE_EATT_CHAN_NUM
#error "CONFIG_BT_NIMBLE_EATT_CHAN_NUM is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_EATT_CHAN_NUM 0

#ifdef CONFIG_BT_NIMBLE_ENABLED
#error "CONFIG_BT_NIMBLE_ENABLED is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ENABLED 1

#ifdef CONFIG_BT_NIMBLE_ENABLE_CONN_REATTEMPT
#error "CONFIG_BT_NIMBLE_ENABLE_CONN_REATTEMPT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ENABLE_CONN_REATTEMPT 1

#ifdef CONFIG_BT_NIMBLE_EXTRA_ADV_FIELDS
#error "CONFIG_BT_NIMBLE_EXTRA_ADV_FIELDS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_EXTRA_ADV_FIELDS 1

#ifdef CONFIG_BT_NIMBLE_GAP_DEVICE_NAME_MAX_LEN
#error "CONFIG_BT_NIMBLE_GAP_DEVICE_NAME_MAX_LEN is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_GAP_DEVICE_NAME_MAX_LEN 31

#ifdef CONFIG_BT_NIMBLE_GAP_SERVICE
#error "CONFIG_BT_NIMBLE_GAP_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_GAP_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_GATT_CLIENT
#error "CONFIG_BT_NIMBLE_GATT_CLIENT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_GATT_CLIENT 1

#ifdef CONFIG_BT_NIMBLE_GATT_MAX_PROCS
#error "CONFIG_BT_NIMBLE_GATT_MAX_PROCS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_GATT_MAX_PROCS 4

#ifdef CONFIG_BT_NIMBLE_GATT_SERVER
#error "CONFIG_BT_NIMBLE_GATT_SERVER is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_GATT_SERVER 1

#ifdef CONFIG_BT_NIMBLE_HCI_EVT_BUF_SIZE
#error "CONFIG_BT_NIMBLE_HCI_EVT_BUF_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_EVT_BUF_SIZE 70

#ifdef CONFIG_BT_NIMBLE_HCI_EVT_HI_BUF_COUNT
#error "CONFIG_BT_NIMBLE_HCI_EVT_HI_BUF_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_EVT_HI_BUF_COUNT 30

#ifdef CONFIG_BT_NIMBLE_HCI_EVT_LO_BUF_COUNT
#error "CONFIG_BT_NIMBLE_HCI_EVT_LO_BUF_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_EVT_LO_BUF_COUNT 8

#ifdef CONFIG_BT_NIMBLE_HCI_UART_CTS_PIN
#error "CONFIG_BT_NIMBLE_HCI_UART_CTS_PIN is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_UART_CTS_PIN 23

#ifdef CONFIG_BT_NIMBLE_HCI_UART_FLOW_CTRL
#error "CONFIG_BT_NIMBLE_HCI_UART_FLOW_CTRL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_UART_FLOW_CTRL 0

#ifdef CONFIG_BT_NIMBLE_HCI_UART_RTS_PIN
#error "CONFIG_BT_NIMBLE_HCI_UART_RTS_PIN is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HCI_UART_RTS_PIN 19

#ifdef CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE
#error "CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE 5120

#ifdef CONFIG_BT_NIMBLE_HR_SERVICE
#error "CONFIG_BT_NIMBLE_HR_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HR_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_HS_PVCY
#error "CONFIG_BT_NIMBLE_HS_PVCY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HS_PVCY 1

#ifdef CONFIG_BT_NIMBLE_HS_STOP_TIMEOUT_MS
#error "CONFIG_BT_NIMBLE_HS_STOP_TIMEOUT_MS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HS_STOP_TIMEOUT_MS 2000

#ifdef CONFIG_BT_NIMBLE_HTP_SERVICE
#error "CONFIG_BT_NIMBLE_HTP_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_HTP_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_IAS_SERVICE
#error "CONFIG_BT_NIMBLE_IAS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_IAS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_IPSS_SERVICE
#error "CONFIG_BT_NIMBLE_IPSS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_IPSS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM
#error "CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_L2CAP_COC_MAX_NUM 0

#ifdef CONFIG_BT_NIMBLE_L2CAP_COC_SDU_BUFF_COUNT
#error "CONFIG_BT_NIMBLE_L2CAP_COC_SDU_BUFF_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_L2CAP_COC_SDU_BUFF_COUNT 1

#ifdef CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE
#error "CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE 1

#ifdef CONFIG_BT_NIMBLE_LLS_SERVICE
#error "CONFIG_BT_NIMBLE_LLS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LLS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_2M_PHY
#error "CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_2M_PHY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_2M_PHY 1

#ifdef CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY
#error "CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY 1

#ifdef CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_ENCRYPTION
#error "CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_ENCRYPTION is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_ENCRYPTION 1

#ifdef CONFIG_BT_NIMBLE_LOG_LEVEL
#error "CONFIG_BT_NIMBLE_LOG_LEVEL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LOG_LEVEL 1

#ifdef CONFIG_BT_NIMBLE_LOG_LEVEL_INFO
#error "CONFIG_BT_NIMBLE_LOG_LEVEL_INFO is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_LOG_LEVEL_INFO 1

#ifdef CONFIG_BT_NIMBLE_MAX_BONDS
#error "CONFIG_BT_NIMBLE_MAX_BONDS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MAX_BONDS 3

#ifdef CONFIG_BT_NIMBLE_MAX_CCCDS
#error "CONFIG_BT_NIMBLE_MAX_CCCDS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MAX_CCCDS 8

#ifdef CONFIG_BT_NIMBLE_MAX_CONNECTIONS
#error "CONFIG_BT_NIMBLE_MAX_CONNECTIONS is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MAX_CONNECTIONS 3

#ifdef CONFIG_BT_NIMBLE_MAX_CONN_REATTEMPT
#error "CONFIG_BT_NIMBLE_MAX_CONN_REATTEMPT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MAX_CONN_REATTEMPT 3

#ifdef CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL
#error "CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MEM_ALLOC_MODE_INTERNAL 1

#ifdef CONFIG_BT_NIMBLE_MEM_OPTIMIZATION
#error "CONFIG_BT_NIMBLE_MEM_OPTIMIZATION is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MEM_OPTIMIZATION 1

#ifdef CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT
#error "CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT 12

#ifdef CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT
#error "CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_COUNT 12

#ifdef CONFIG_BT_NIMBLE_MSYS_1_BLOCK_SIZE
#error "CONFIG_BT_NIMBLE_MSYS_1_BLOCK_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MSYS_1_BLOCK_SIZE 256

#ifdef CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT
#error "CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_COUNT 24

#ifdef CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE
#error "CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_MSYS_2_BLOCK_SIZE 320

#ifdef CONFIG_BT_NIMBLE_NVS_PERSIST
#error "CONFIG_BT_NIMBLE_NVS_PERSIST is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_NVS_PERSIST 1

#ifdef CONFIG_BT_NIMBLE_PINNED_TO_CORE
#error "CONFIG_BT_NIMBLE_PINNED_TO_CORE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_PINNED_TO_CORE 0

#ifdef CONFIG_BT_NIMBLE_PINNED_TO_CORE_0
#error "CONFIG_BT_NIMBLE_PINNED_TO_CORE_0 is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_PINNED_TO_CORE_0 1

#ifdef CONFIG_BT_NIMBLE_PRINT_ERR_NAME
#error "CONFIG_BT_NIMBLE_PRINT_ERR_NAME is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_PRINT_ERR_NAME 1

#ifdef CONFIG_BT_NIMBLE_PROX_SERVICE
#error "CONFIG_BT_NIMBLE_PROX_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_PROX_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_RECONFIG_MTU
#error "CONFIG_BT_NIMBLE_RECONFIG_MTU is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_RECONFIG_MTU 1

#ifdef CONFIG_BT_NIMBLE_ROLE_BROADCASTER
#error "CONFIG_BT_NIMBLE_ROLE_BROADCASTER is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ROLE_BROADCASTER 1

#ifdef CONFIG_BT_NIMBLE_ROLE_CENTRAL
#error "CONFIG_BT_NIMBLE_ROLE_CENTRAL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ROLE_CENTRAL 1

#ifdef CONFIG_BT_NIMBLE_ROLE_OBSERVER
#error "CONFIG_BT_NIMBLE_ROLE_OBSERVER is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ROLE_OBSERVER 1

#ifdef CONFIG_BT_NIMBLE_ROLE_PERIPHERAL
#error "CONFIG_BT_NIMBLE_ROLE_PERIPHERAL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_ROLE_PERIPHERAL 1

#ifdef CONFIG_BT_NIMBLE_RPA_TIMEOUT
#error "CONFIG_BT_NIMBLE_RPA_TIMEOUT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_RPA_TIMEOUT 900

#ifdef CONFIG_BT_NIMBLE_SECURITY_ENABLE
#error "CONFIG_BT_NIMBLE_SECURITY_ENABLE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SECURITY_ENABLE 1

#ifdef CONFIG_BT_NIMBLE_SM_LEGACY
#error "CONFIG_BT_NIMBLE_SM_LEGACY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_LEGACY 1

#ifdef CONFIG_BT_NIMBLE_SM_LVL
#error "CONFIG_BT_NIMBLE_SM_LVL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_LVL 0

#ifdef CONFIG_BT_NIMBLE_SM_SC
#error "CONFIG_BT_NIMBLE_SM_SC is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_SC 1

#ifdef CONFIG_BT_NIMBLE_SM_SC_LVL
#error "CONFIG_BT_NIMBLE_SM_SC_LVL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_SC_LVL 0

#ifdef CONFIG_BT_NIMBLE_SM_SC_ONLY
#error "CONFIG_BT_NIMBLE_SM_SC_ONLY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_SC_ONLY 0

#ifdef CONFIG_BT_NIMBLE_SM_SIGN_CNT
#error "CONFIG_BT_NIMBLE_SM_SIGN_CNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SM_SIGN_CNT 1

#ifdef CONFIG_BT_NIMBLE_SPS_SERVICE
#error "CONFIG_BT_NIMBLE_SPS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SPS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_STATIC_TO_DYNAMIC
#error "CONFIG_BT_NIMBLE_STATIC_TO_DYNAMIC is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_STATIC_TO_DYNAMIC 1

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_APPEARANCE
#error "CONFIG_BT_NIMBLE_SVC_GAP_APPEARANCE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEARANCE 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM
#error "CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHN
#error "CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHN is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHN 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHR
#error "CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHR is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ATHR 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ENC
#error "CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ENC is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_APPEAR_WRITE_PERM_ENC 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_CAR_CHAR_NOT_SUPP
#error "CONFIG_BT_NIMBLE_SVC_GAP_CAR_CHAR_NOT_SUPP is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_CAR_CHAR_NOT_SUPP 1

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_CENT_ADDR_RESOLUTION
#error "CONFIG_BT_NIMBLE_SVC_GAP_CENT_ADDR_RESOLUTION is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_CENT_ADDR_RESOLUTION -1

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME
#error "CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_DEVICE_NAME "nimble"

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM
#error "CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHEN
#error "CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHEN is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHEN 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHOR
#error "CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHOR is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_AUTHOR 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_ENC
#error "CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_ENC is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_NAME_WRITE_PERM_ENC 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL
#error "CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MAX_CONN_INTERVAL 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL
#error "CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_PPCP_MIN_CONN_INTERVAL 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SLAVE_LATENCY
#error "CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SLAVE_LATENCY is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SLAVE_LATENCY 0

#ifdef CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SUPERVISION_TMO
#error "CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SUPERVISION_TMO is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_SVC_GAP_PPCP_SUPERVISION_TMO 0

#ifdef CONFIG_BT_NIMBLE_TASK_STACK_SIZE
#error "CONFIG_BT_NIMBLE_TASK_STACK_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TASK_STACK_SIZE 5120

#ifdef CONFIG_BT_NIMBLE_TPS_SERVICE
#error "CONFIG_BT_NIMBLE_TPS_SERVICE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TPS_SERVICE 1

#ifdef CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT
#error "CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TRANSPORT_ACL_FROM_LL_COUNT 24

#ifdef CONFIG_BT_NIMBLE_TRANSPORT_ACL_SIZE
#error "CONFIG_BT_NIMBLE_TRANSPORT_ACL_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TRANSPORT_ACL_SIZE 255

#ifdef CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT
#error "CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_COUNT 30

#ifdef CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT
#error "CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_DISCARD_COUNT 8

#ifdef CONFIG_BT_NIMBLE_TRANSPORT_EVT_SIZE
#error "CONFIG_BT_NIMBLE_TRANSPORT_EVT_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_TRANSPORT_EVT_SIZE 70

#ifdef CONFIG_BT_NIMBLE_USE_ESP_TIMER
#error "CONFIG_BT_NIMBLE_USE_ESP_TIMER is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_USE_ESP_TIMER 1

#ifdef CONFIG_BT_NIMBLE_UTIL_API
#error "CONFIG_BT_NIMBLE_UTIL_API is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_UTIL_API 1

#ifdef CONFIG_BT_NIMBLE_VS_SUPPORT
#error "CONFIG_BT_NIMBLE_VS_SUPPORT is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_VS_SUPPORT 1

#ifdef CONFIG_BT_NIMBLE_WHITELIST_SIZE
#error "CONFIG_BT_NIMBLE_WHITELIST_SIZE is fixed by EspBle for the original ESP32 and cannot be overridden"
#endif
#define CONFIG_BT_NIMBLE_WHITELIST_SIZE 12

#endif /* ESPBLE_NIMBLE_CONFIG_H */
