/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPBLE_VERSION_H
#define ESPBLE_VERSION_H

#define ESPBLE_VERSION_MAJOR 1
#define ESPBLE_VERSION_MINOR 2
#define ESPBLE_VERSION_PATCH 0
#define ESPBLE_VERSION_STR "1.2.0"

#endif // ESPBLE_VERSION_H
