/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPBLE_VERSION_H
#define ESPBLE_VERSION_H

#define ESPBLE_VERSION_MAJOR 0
#define ESPBLE_VERSION_MINOR 1
#define ESPBLE_VERSION_PATCH 0
#define ESPBLE_VERSION_STR "0.1.0"

#endif // ESPBLE_VERSION_H
