/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef ESPBLE_VERSION_H
#define ESPBLE_VERSION_H

#define ESPBLE_VERSION_MAJOR 1
#define ESPBLE_VERSION_MINOR 3
#define ESPBLE_VERSION_PATCH 0
#define ESPBLE_VERSION_STR "1.3.0"

#endif // ESPBLE_VERSION_H
